SELECT PERSONAL_DETAILS_ID FROM PERSON_DEPARTMENT_TAG GROUP BY PERSONAL_DETAILS_ID;
DELETE FROM PERSON_TYPE;  
DELETE FROM PERSON_DEPARTMENT_TAG;
DELETE FROM RFID_TAG ;
DELETE FROM PERSONAL_DETAILS;

SELECT T3.NAME ,T2.CODE,T6.DOOR_NO,T1.RFID_TAG_ID  ,T6.MODULE_ID, T7.RFID_READER_ID 
FROM PERSON_DEPARTMENT_TAG T1,
PERSONAL_DETAILS T2,
DEPARTMENT T3,
RFID_TAG T4,
DEPARTMENT_MODULE_GROUP T5,
MODULE T6,
RFID_READER T7
WHERE T1.DEACTIVATION_DATE  IS NULL
AND T1.PERSONAL_DETAILS_ID =T2.PERSONAL_DETAILS_ID 
AND T1.DEPARTMENT_ID =T3.DEPARTMENT_ID 
AND T3.DEACTIVATION_DATE  IS NULL
AND T1.RFID_TAG_ID =T4.RFID_TAG_ID 
AND T4.DEACTIVATION_DATE  IS NULL
AND T1.DEPARTMENT_ID =T5.DEPARTMENT_ID 
AND T5.DEACTIVATION_DATE  IS NULL
AND T5.MODULE_ID =T6.MODULE_ID 
AND T6.DEACTIVATION_DATE  IS NULL
AND T6.MODULE_ID =T7.MODULE_ID 
AND T7.DEACTIVATION_DATE  IS NULL
AND T2.CODE ='PR1'

SELECT T3.NAME ,T2.CODE,T6.DOOR_NO,T1.RFID_TAG_ID  ,T6.MODULE_ID, T7.RFID_READER_ID 
FROM PERSON_DEPARTMENT_TAG T1,
PERSONAL_DETAILS T2,
DEPARTMENT T3,
RFID_TAG T4,
DEPARTMENT_MODULE_GROUP T5,
MODULE T6,
RFID_READER T7,
PERSON_DEPARTMENT_TAG_LOG T8
WHERE T1.DEACTIVATION_DATE  IS NULL
AND T1.PERSONAL_DETAILS_ID =T2.PERSONAL_DETAILS_ID 
AND T1.DEPARTMENT_ID =T3.DEPARTMENT_ID 
AND T3.DEACTIVATION_DATE  IS NULL
AND T1.RFID_TAG_ID =T4.RFID_TAG_ID 
AND T4.DEACTIVATION_DATE  IS NULL
AND T1.DEPARTMENT_ID =T5.DEPARTMENT_ID 
AND T5.DEACTIVATION_DATE  IS NULL
AND T5.MODULE_ID =T6.MODULE_ID 
AND T6.DEACTIVATION_DATE  IS NULL
AND T6.MODULE_ID =T7.MODULE_ID 
AND T7.DEACTIVATION_DATE  IS NULL
AND T2.CODE ='PR1'
AND T1.MODULE_ID =T8.MODULE_ID 
AND T1.PERSONAL_DEPARTMENT_ID  =T8.PERSON_DEPARTMENT_TAG_ID 

SELECT
T6.NAME AS DEPTNAME, 
T7.CODE,
T3.DOOR_NO ,
T5.LOG,
T5.LOG_TIME
FROM PERSON_DEPARTMENT_TAG T1,
DEPARTMENT_MODULE_GROUP T2,
MODULE  T3,
RFID_READER  T4,
PERSON_DEPARTMENT_TAG_LOG  T5,
DEPARTMENT T6,
PERSONAL_DETAILS T7 
WHERE T1.DEACTIVATION_DATE  IS NULL
AND T1.DEPARTMENT_ID =T2.DEPARTMENT_ID 
AND T2.DEACTIVATION_DATE  IS NULL
AND T2.MODULE_ID=T3.MODULE_ID
AND T3.DEACTIVATION_DATE  IS NULL
AND T3.MODULE_ID=T4.MODULE_ID 
AND T4.DEACTIVATION_DATE  IS NULL
AND T4.MODULE_ID =T5.MODULE_ID 
AND T4.RFID_READER_ID =T5.RFID_READER_ID 
AND T1.RFID_TAG_ID =T5.TAG_ID 
AND T5.PERMISSION IN ('GRANTED','DENIED')
AND T5.LOG_TIME =(SELECT MAX(LOG_TIME) 
FROM PERSON_DEPARTMENT_TAG_LOG  
WHERE TAG_ID=T5.TAG_ID 
AND MODULE_ID=T5.MODULE_ID 
AND RFID_READER_ID=T5.RFID_READER_ID 
AND PERMISSION=T5.PERMISSION
GROUP BY MODULE_ID,RFID_READER_ID,TAG_ID)
AND T1.DEPARTMENT_ID =T6.DEPARTMENT_ID 
AND T6.DEACTIVATION_DATE  IS NULL
AND T1.PERSONAL_DETAILS_ID =T7.PERSONAL_DETAILS_ID

SELECT T1.NAME, T2.CODE,Get_Date(T7.LOG_TIME)  as DATE,'D'||T5.DOOR_NO AS DOOR_NO ,T7.LOG,Get_Time(T7.LOG_TIME) as TIME 
FROM PERSON_TYPE T1,
PERSONAL_DETAILS T2,
PERSON_DEPARTMENT_TAG T3,
DEPARTMENT_MODULE_GROUP T4,
MODULE T5,
RFID_READER T8,
DEPARTMENT T6,
PERSON_DEPARTMENT_TAG_LOG T7
WHERE T1.DEACTIVATION_DATE IS NULL
AND T1.DEPT ='DEPT'
AND T1.PERSON_TYPE_ID =T2.PERSON_TYPE_ID 
AND T2.PERSONAL_DETAILS_ID =T3.PERSONAL_DETAILS_ID
AND T3.DEACTIVATION_DATE IS NULL
AND T3.DEPARTMENT_ID  =T4.DEPARTMENT_ID  
AND T4.DEACTIVATION_DATE  IS NULL
AND T4.MODULE_ID =T5.MODULE_ID 
AND T5.DEACTIVATION_DATE IS NULL
AND T5.MODULE_ID =T8.MODULE_ID 
AND T8.DEACTIVATION_DATE IS NULL
AND T3.DEPARTMENT_ID  =T6.DEPARTMENT_ID  
AND T6.DEACTIVATION_DATE IS NULL
AND T2.PERSONAL_DETAILS_ID = T7.TAG_ID 
AND T7.PERMISSION IN ('GRANTED')
AND T5.MODULE_ID=T7.MODULE_ID
AND T8.RFID_READER_ID =T7.RFID_READER_ID
AND T7.LOG='IN'
AND T7.LOG_TIME=(SELECT MIN(LOG_TIME)
                                    FROM PERSON_DEPARTMENT_TAG_LOG 
                                    WHERE LOG =T7.LOG
                                    AND MODULE_ID =T7.MODULE_ID 
                                    AND PERMISSION =T7.PERMISSION 
                                    AND RFID_READER_ID =T7.RFID_READER_ID 
                                    AND TAG_ID=T7.TAG_ID
                                     GROUP BY TAG_ID ,MODULE_ID ,RFID_READER_ID,LOG    )
UNION 
SELECT T1.NAME, T2.CODE,Get_Date(T7.LOG_TIME)  as DATE,'D'||T5.DOOR_NO AS DOOR_NO ,T7.LOG,Get_Time(T7.LOG_TIME) as TIME 
FROM PERSON_TYPE T1,
PERSONAL_DETAILS T2,
PERSON_DEPARTMENT_TAG T3,
DEPARTMENT_MODULE_GROUP T4,
MODULE T5,
RFID_READER T8,
DEPARTMENT T6,
PERSON_DEPARTMENT_TAG_LOG T7
WHERE T1.DEACTIVATION_DATE IS NULL
AND T1.DEPT ='DEPT'
AND T1.PERSON_TYPE_ID =T2.PERSON_TYPE_ID 
AND T2.PERSONAL_DETAILS_ID =T3.PERSONAL_DETAILS_ID
AND T3.DEACTIVATION_DATE IS NULL
AND T3.DEPARTMENT_ID  =T4.DEPARTMENT_ID  
AND T4.DEACTIVATION_DATE  IS NULL
AND T4.MODULE_ID =T5.MODULE_ID 
AND T5.DEACTIVATION_DATE IS NULL
AND T5.MODULE_ID =T8.MODULE_ID 
AND T8.DEACTIVATION_DATE IS NULL
AND T3.DEPARTMENT_ID  =T6.DEPARTMENT_ID  
AND T6.DEACTIVATION_DATE IS NULL
AND T2.PERSONAL_DETAILS_ID = T7.TAG_ID 
AND T7.PERMISSION IN ('GRANTED')
AND T5.MODULE_ID=T7.MODULE_ID
AND T8.RFID_READER_ID =T7.RFID_READER_ID
AND T7.LOG='OUT'
AND T7.LOG_TIME=(SELECT MIN(LOG_TIME)
                                    FROM PERSON_DEPARTMENT_TAG_LOG 
                                    WHERE LOG =T7.LOG
                                    AND MODULE_ID =T7.MODULE_ID 
                                    AND PERMISSION =T7.PERMISSION 
                                    AND RFID_READER_ID =T7.RFID_READER_ID 
                                    AND TAG_ID=T7.TAG_ID
                                     GROUP BY TAG_ID ,MODULE_ID ,RFID_READER_ID,LOG    )
ORDER BY 1,2,3,4,6
    )


-------------------------------
-- functions
-------------------------------
CREATE OR REPLACE ALIAS GET_DATE AS  $$
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collection;
import java.util.HashSet;
import java.util.stream.Collectors;
import java.util.Date;
import java.text.SimpleDateFormat;  
@CODE
String getDate(final Long yourmilliseconds) {
SimpleDateFormat sdf = new SimpleDateFormat("MMM dd,yyyy");
Date resultdate = new Date(yourmilliseconds);
return sdf.format(resultdate);
}
$$;

CREATE OR REPLACE ALIAS GET_TIME AS  $$
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collection;
import java.util.HashSet;
import java.util.stream.Collectors;
import java.util.Date;
import java.text.SimpleDateFormat;  
@CODE
String getTime(final Long yourmilliseconds) {
SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
Date resultdate = new Date(yourmilliseconds);
return sdf.format(resultdate);
}
$$;


CREATE OR REPLACE ALIAS GET_DATE_TIME1 AS  $$
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collection;
import java.util.HashSet;
import java.util.stream.Collectors;
import java.util.Date;
import java.text.SimpleDateFormat;  
@CODE
String getDateTime1(final Long yourmilliseconds) {
SimpleDateFormat sdf = new SimpleDateFormat("MMM dd,yyyy HH:mm");
Date resultdate = new Date(yourmilliseconds);
return sdf.format(resultdate);
}
$$;

